name: nigerian_igbo
version: 0.0.1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_cli: ^1.9.1
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  encrypt: ^5.0.3
  logger: ^2.6.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  flutter_test:
    sdk: flutter

dependency_overrides:
  fluttertoast: ^8.2.12
  platform: ^3.1.6
  collection: ^1.19.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true